# Metadata and output settings
metadata_file: "config/metadata.csv"  # CSV file containing sample information, column names must be: sample, group, library_layout, input_r1, input_r2
outdir: "results/test_data"            # Directory to store output data

# Quality Control settings
qc_tool_path: "/opt/fastp/0.23.4/bin/fastp"  # Path to fastp for quality control
qc_threads: 4                                  # Number of cores for quality control

# Alignment settings
alignment_tool_path: "/opt/star/2.7.11a/bin/STAR"  # Path to tools for alignment
alignment_threads: 8                                # Number of cores for alignment
reference_genome_path: "/public/index/star/mus_musculus/GRCm39/"  # Reference genome for alignment

# Quantification settings
quantification_tool_path: "/opt/subread/2.0.6/bin/featureCounts"  # Path to featureCounts for quantification
quantification_threads: 2                                           # Number of cores for featureCounts
gene_annotation_path: "/public/genome/mus_musculus/GRCm39/gencode.vM33.annotation.gtf"  # GTF file for gene annotation

# (Optional) Additional parameters can be added here.
# E.g., trimming length for fastp, specific flags for STAR or featureCounts etc.
